# render.yaml
services:
  # 1. Base de Datos PostgreSQL (Render la proporciona y debes copiar su DATABASE_URL manualmente)
  - type: pserv
    name: postgres-db
    plan: free

  # 2. Servidor Web principal: Django
  - type: web
    name: beauty-shop
    runtime: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: postgres://USUARIO:CONTRASENA@HOST:5432/NOMBRE_BASE
        # ⚠️ Reemplaza esto con el valor de "Internal Database URL" de tu servicio PostgreSQL
      - key: ALLOWED_HOSTS
        value: beauty-shop.onrender.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        value: tu_correo@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: tu_contraseña_de_aplicación
      - key: DEFAULT_FROM_EMAIL
        value: tu_correo@gmail.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://beauty-shop.onrender.com
