# render.yaml

services:
  # 1. El Servidor Web (Tu aplicación Django)
  - type: web
    name: beauty-shop
    runtime: python
    plan: free
    branch: main

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn config.wsgi:application"

    healthCheckPath: /

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # 2. El Worker para Tareas en Segundo Plano (Celery)
  - type: worker
    name: beauty-shop-worker
    runtime: python
    plan: free
    branch: main

    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config.celery worker --loglevel=info"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        fromService:
          name: beauty-shop
          type: web
          envVarKey: SECRET_KEY
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # 3. El Cache/Broker de Redis para Celery <-- REDIS MOVIDO AQUÍ
  - type: redis
    name: redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru

# Definición de los servicios de base de datos que usaremos
databases:
  # 4. La Base de Datos PostgreSQL <-- SOLO POSTGRES QUEDA AQUÍ
  - name: postgres-db
    plan: free