# render.yaml
# render.yaml

services:
  # 1. Base de Datos PostgreSQL
  - type: pserv
    name: postgres-db
    plan: free

  # 2. Servidor Web: Django App
  - type: web
    name: beauty-shop
    runtime: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: internalConnectionString
