# render.yaml

# 1. Declaramos la base de datos en su bloque correcto.
databases:
  - name: postgres-db
    plan: free

# 2. Declaramos los servicios que la utilizarán.
services:
  # Servicio de Redis
  - type: redis
    name: redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Servicio Web (Django)
  - type: web
    name: beauty-shop
    runtime: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn config.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: internalConnectionString # <-- LA CORRECCIÓN CLAVE
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  # Worker de Celery
  - type: worker
    name: beauty-shop-worker
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config.celery worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        fromService:
          name: beauty-shop
          type: web
          envVarKey: SECRET_KEY
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: internalConnectionString # <-- LA CORRECCIÓN CLAVE
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString